memo/urls.py
from django.urls import path
from .views import BookmarkListView, create_bookmark, add_bookmark, BookmarkDetailView, BookmarkUpdateView, BookmarkDeleteView

urlpatterns = [
    path('', BookmarkListView.as_view(), name='list'),
    path('add/', create_bookmark, name='add'),
    path('add/add_bookmark', add_bookmark, name='add_bookmark'),
    path('detail/<int:pk>/', BookmarkDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BookmarkDeleteView.as_view(), name='delete'),
]

paperEasy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('paperEasyapp.urls')),
                  path('users/', include('django.contrib.auth.urls')),
                  path('users/', include('users.urls')),
                  path('bookmark/', include('memo.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

memo/models.py
from django.db import models
from django.contrib.auth.models import User


class Bookmark(models.Model):
    site_name = models.CharField(max_length=500)
    url = models.URLField('Site URL')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return " contents: " + self.site_name + ", url: " + self.url
        # 객체를 출력할 때 나타나는 값

memo/forms.py
from django import forms
from .models import Bookmark

memo/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy

from .models import Bookmark


class BookmarkListView(ListView):
    model = Bookmark
    paginate_by = 10


def create_bookmark(request):
    return render(request, 'memo/bookmark_create.html')



def add_bookmark(request):
    if request.method == 'POST':
        bookmark = Bookmark()
        bookmark.site_name = request.POST['title']
        bookmark.author = request.user
        bookmark.url = "/third?theid=" + str(request.POST['pmc_id'])
        bookmark.save()
        message = 'created successful'
        return HttpResponse(message)





class BookmarkDetailView(DetailView):
    model = Bookmark


class BookmarkUpdateView(UpdateView):
    model = Bookmark
    fields = ['site_name', 'url']
    success_url = reverse_lazy('list')
    template_name_suffix = '_update'


class BookmarkDeleteView(DeleteView):
    model = Bookmark
    success_url = reverse_lazy('list')

memo/templates/memo/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %} Confirm Delete {% endblock %}

{% block content %}
<style type="text/css">
     @import url('https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap');
    body{
      background-image: linear-gradient(0deg, #08AEEA 0%, #2AF598 100%);
      background-repeat: no-repeat;
      background-attachment: fixed;
    }
    #text{
        font-family: 'Caveat', cursive;
        font-size: 20px;
        box-shadow:3px 3px 6px #000808;
        background-color: #CA7B8C;
        color: black;
    }
    #delete_button{
        font-family: 'Caveat', cursive;
        font-size: 20px;
        box-shadow:3px 3px 6px #000808;
        background-color: #7BB3CA;
        color: black;
        position:fixed;
        left: 1130px;
        top: 230px;
    }
</style>
<br><br><br>
    <form action = "" method = "post">
            {% csrf_token %}
            <div id='text' class="alert alert-danger">Do you want to delete &nbsp "{{object}}"?</div>
            <input type = "submit" id="delete_button" value="Delete" class = "btn btn-info btn-sm">
    </form>

{% endblock %}

memo/templates/memo/bookmark_create.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<style type="text/css">
    @import url('https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap');
    body{
      background-image: linear-gradient(0deg, #08AEEA 0%, #2AF598 100%);
      background-repeat: no-repeat;
      background-attachment: fixed;
    }

    #send_form{
      font-family: 'Caveat', cursive;
      font-size: 17px;
      text-align:center;
      width: 80px;
      position: fixed;
      left: 160px;
      top: 140px;

    }

    #title{
      font-family: 'Caveat', cursive;
      font-size: 15px;
      text-align:center;
      width: 390px;

      position: fixed;
      left: 6px;
      top: 70px;
    }
</style>


 <script type="text/javascript">
 		    $(function() {

            $('#send_form').submit(function(e) {
                // 원래의 동작 금지(ex. 링크 클릭하면 주소 이동 금지)
                e.preventDefault();
                data = $(this).serialize
                // $(this) : 해당 이벤트 발생된 주체
                // serialize : 데이트 전송 편하도록 직렬화

                // ajax로 데이터 전송
                $.ajax({
                    url: "{% url 'add_bookmark' %}", // ajax로 데이터 교환할 페이지 주소
                    method: "POST",
                    data: data
                }).done(function() {
                    alert(data.message);
                });
                return false;
            });
        });

        /*
        데이터를 전송하는 페이지(HTML), 데이터를 전송받는 페이지(django view)
        HTML - 회원가입, 좋아요 데이터 전송
        -> 장고측 뷰가 데이터를 받아 모델 처리, 로직 처리
        -> 모델처리가 완료되면 메시지, 혹은 처리 결과 데이터를 다시 HTML로 전송
        -> HTML은 응답받은 데이터를 가지고 화면에 정보 출력

        $.ajax({
            url: "클라이언트가 요청 보낼 서버의 URL 주소",
            method:"POST",          // HTTP 요청 방식(GET, POST)
            type: "json",           // 서버에서 보내줄 데이터의 타입(default값으로 json으로 되어있다.)
            data: {name: "홍길동"}   // HTTP 요청과 함께 서버로 보낼 데이터

        }).done(function(data) {    // HTTP 요청 성공 시, 요청한 데이터가 done() 메소드로 전달

        }).fail(function(xhr, data) {     // HTTP 요청 실패 시, 오류와 상태에 관한 정보가 fail() 메소드로 전달

        }).always(function(xhr, data) {   // HTTP 요청의 성공여부와는 상관없이 언제나 always()메소드 실행

        });
        출처: [조누스의 걸음마 개발 로그] https://chohyeonkeun.github.io/2019/05/10/190510-django-Ajax/
        */



        function getText(){
            document.getElementById("pmc_id").value = opener.document.getElementById("theid").value;
        }
   </script>




</head>
<br><br><br>


<form action="add_bookmark" method="POST" class="post-form">
        {% csrf_token %}
        <input  type="hidden" name="pmc_id" id="pmc_id" class="form-control form-control-sm" type="text"/>
		<input  name="title" id="title" class="form-control form-control-sm" placeholder="The title" type="text"/>
    {% load static %}
        <button type="submit" onclick="getText()" id="send_form" class="btn btn-secondary">Add</button>
</form>

memo/templates/memo/bookmark_detail.html
{% extends 'base.html' %}

{% block title %} Bookmark {% endblock %}

{% block content %}
<style type="text/css">
     @import url('https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap');
    body{
      background-image: linear-gradient(0deg, #08AEEA 0%, #2AF598 100%);
      background-repeat: no-repeat;
      background-attachment: fixed;
    }
</style>
    {{object.site_name}}<br/>
    {{object.url}}
{% endblock %}

memo/templates/memo/bookmark_list.html
{% extends 'base.html' %}

{% block title %} Bookmark {% endblock %}

{% block content %}
<style type="text/css">
     @import url('https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap');
    body{
      background-image: linear-gradient(0deg, #08AEEA 0%, #2AF598 100%);
      background-repeat: no-repeat;
      background-attachment: fixed;
    }
    #modify_button{
        font-family: 'Caveat', cursive;
        font-size: 15px;
        box-shadow:3px 3px 6px #000808;
        background-color: #7BB3CA;
        color: black;

    }
    #delete_button{
        font-family: 'Caveat', cursive;
        font-size: 15px;
        box-shadow:3px 3px 6px #000808;
        background-color: #7BB3CA;
        color: black;
        border: 0px;
    }
</style>
    <br>
    <p></p>
    <table class = "table">
        <thead>
            <tr>
                <th scope = "col" style="font-family: 'Caveat', cursive; box-shadow:2px 2px 6px #000808; font-size: 20px; text-align: center; background-color: rgba( 255, 255, 255, 0.3 );">Title</th>
                <th scope = "col" style="font-family: 'Caveat', cursive; box-shadow:2px 2px 6px #000808; font-size: 20px; text-align: center; background-color: rgba( 255, 255, 255, 0.3 );">URL</th>
                <th scope = "col" style="font-family: 'Caveat', cursive; box-shadow:2px 2px 6px #000808; font-size: 20px; text-align: center; background-color: rgba( 255, 255, 255, 0.3 );">Modify</th>
                <th scope = "col" style="font-family: 'Caveat', cursive; box-shadow:2px 2px 6px #000808; font-size: 20px; text-align: center; background-color: rgba( 255, 255, 255, 0.3 );">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for bookmark in object_list %}
            <tr>

                {% if user.id == bookmark.author.id %}
                <td>{{bookmark.site_name}}</td>
                <td><a href="{{bookmark.url}}" target="_blank" >{{bookmark.url}}</a></td>
                <td><a href="{% url 'update' pk=bookmark.id %}" id='modify_button' class="btn btn-success btn-sm">Modify</a></td>
                <td><a href="{% url 'delete' pk=bookmark.id %}" id='delete_button' class="btn btn-success btn-sm">Delete</a></td>
                {% endif %}

            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block pagination %}
{% if is_paginated %}
<ul class="pagination justify-content-center pagination-sm">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="{% url 'list' %}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">Previous</a>
    </li>
    {% endif %}

    {% for object in page_obj.paginator.page_range %}
    <li class="page-item {% if page_obj.number == forloop.counter %} disabled {% endif %} ">
        <a class="page-link" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
    </li>
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="{% url 'list' %}?page={{ page_obj.next_page_number }}">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">Next</a>
    </li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}

memo/templates/memo/bookmark_update.html
{% extends 'base.html' %}

{% block title %} Bookmark {% endblock %}

{% block content %}
<style type="text/css">
    @import url('https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap');
    body{
      background-image: linear-gradient(0deg, #08AEEA 0%, #2AF598 100%);
      background-repeat: no-repeat;
      background-attachment: fixed;
    }
    .url{
        font-family: 'Caveat', cursive;
        font-size: 30px;
    }
    #site_name{
        font-family: 'Caveat', cursive;
        font-size: 20px;
    }
    #update_button{
        border-radius: 4px solid;
        box-shadow:3px 3px 6px #000808;
        position: fixed;
        left: 1130px;
        top: 430px;
    }
</style>
<br><br><br>

    <form action = "" method = "post">
        {% csrf_token %}
        <p>
            <label for="id_site_name" style="font-family: 'Caveat', cursive; font-size: 30px;" >Site name:</label> <input type="text" id='site_name' class="form-control" name="site_name"  maxlength="500" required id="id_site_name">
        </p>

        <p class="url">
            <label for="id_url" >Site URL:</label> <input type="url" class="form-control" name="url" maxlength="200" required id="id_url">
        </p>
        <input type = "submit" value="Update" id='update_button' class = "btn btn-info brn-sm">
    </form>
{% endblock %}